codecov:
  require_ci_to_pass: yes

coverage:
  precision: 2
  round: down
  range: "70...100"
  notify:
    slack:
      default:
        url: "https://hooks.slack.com/services/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"
        threshold: 1%
  status:
    project: yes
    patch: yes
    changes: no
  
parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: no